accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomePageView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', HomePageView.as_view(), name='home'),
]

posts/urls.py
from django.urls import path

from .views import PostUpdateView, PostCreateView, PostDetailView, PostListView


app_name = 'posts'

urlpatterns = [
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('new/', PostCreateView.as_view(), name='create'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('', PostListView.as_view(), name='list'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Postable(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    message = models.TextField()

    class Meta:
        abstract = True


class Post(Postable):
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', args=[str(self.id)])


class Comment(Postable):
    commented_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('posts:detail', args=[str(self.post.id)])

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

posts/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'commented_by']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic

from users.forms import CustomUserCreationForm


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blog_project/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'

posts/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from . import forms
from . import models


class PostListView(ListView):
    model = models.Post
    template_name = 'posts/list.html'
    ordering = 'created'


class PostDetailView(FormMixin, DetailView):
    model = models.Post
    template_name = 'posts/detail.html'
    form_class = forms.CommentForm

    def get_success_url(self):
        return reverse('posts-detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['comments'] = self.object.comment_set.all()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.post = self.get_object()
        new_comment.save()
        return super(PostDetailView, self).form_valid(form)


class PostCreateView(LoginRequiredMixin, CreateView):
    # CreateView
    model = models.Post
    template_name = 'posts/create.html'
    fields = '__all__'

    # LoginRequiredMixin
    login_url = 'login'
    permission_denied_message = 'Log in to create a new post'


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    # UpdateView
    model = models.Post
    template_name = 'posts/update.html'
    fields = ['message', 'title']

    # PermissionRequiredMixin
    login_url = 'login'
    permission_denied_message = 'You can only edit your own posts'
    permission_required = 'posts.change_post'

users/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Post</h1>
    <div class="post-create">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Publish">
        </form>
    </div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Post details</h1>
    <div class="post-details">
        <h2>{{ post.title }}</h2>
        <p>By {{ post.posted_by }}</p>
        <p>{{ post.message }}</p>
        <p>Created: {{ post.created }}</p>
        <p>Modified: {{ post.modified }}</p>
        <a href="{% url 'posts:update' pk=post.pk%}">Edit</a>
    </div>
    <div class="comments-container">
    <div class="comment-field">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Comment">
        </form>
    </div>
    <div class="comments-list">
        {% for comment in comments %}
            <div class="comment-item">
                <p>{{ comment.message }}</p>
                <p><strong>{{ comment.commented_by }}</strong></p>
                <a>{{ comment.created }}</a>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid padding-bottom padding-top">
    <div class="row featured text-center">
        <div class="col-12">
            <h1 class="display-4">Posts</h1>
            <hr class="center">
        </div>
    </div>
    </div>

    <div class="container-fluid padding">
    <div class="row padding">
        {% for post in post_list %}
        <div class="col-sm-12 col-md-6 col-lg-4 card-deck">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text">by {{ post.posted_by }}</p>
                    <p class="card-text">{{ post.message }}</p>
                    <p class="card-text">{{ post.created }}</p>
                    <a class="card-link" href="{% url 'posts:detail' pk=post.id %}">Read more</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Post</h1>
    <div class="post-edit">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Djogger{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Djogger</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigationBar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navigationBar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:list' %}">List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create' %}">New Post</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
             {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="#">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron text-center">
        <h1 class="display-1 text-uppercase">Djogger</h1>
        <h3>Share your thoughts</h3>
    </div>
    <div class="container-fluid text-center">
        <div class="row padding">
            <div class="col">
                {% if user.is_authenticated %}
                    <h1 class="display-5">Continue where you left off</h1>
                {% else %}
                    <h1 class="display-5">Get started</h1>
                {% endif %}
            <hr class="center">
            </div>
        </div>
        <div class="row padding">
            {% if user.is_authenticated %}
                <div class="col">
                    <a href="{% url 'posts:list' %}" class="btn btn-outline-secondary" role="button">List</a>
                    <a href="{% url 'posts:create' %}" class="btn btn-primary" role="button">New Post</a>
                </div>
            {% else %}
                <div class="col">
                    <a href="{% url 'posts:list' %}" class="btn btn-outline-secondary" role="button">List</a>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-primary" role="button">Signup</a>
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary" role="button">Sign In</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}